
services:
  simple_ui_docker:
    image: manologcode/simple_ui_docker
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple_ui_docker
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5001"]
    ports:
      - 5001:5001
    environment:
      - TITLE=Servidor de Descargas
    volumes:
      - ./app:/app
      - /var/run/docker.sock:/var/run/docker.sock

